### ISSUE TITLE
"pop from empty list" during the process of reproducing VAE training

### ISSUE THREAD

**Issue by Glisten-5481** [ziqihuangg/Collaborative-Diffusion#33]
Hello, sorry to bother you. I want to ask if it's normal to see "pop from empty list" during the process of reproducing VAE training. ![QQ图片20240418111808](https://github.com/ziqihuangg/Collaborative-Diffusion/assets/100678812/1cc6e542-7e43-48e7-97d0-f7512a68c8be).

**Comment by ziqihuangg** [comment]
Hi, thanks for the question. I guess this is a common problem of the LDM / Stable Diffusion codebase. It's because in `main.py`, the ImageLogger's self.log_steps list conducts the pop() operation periodically, but the list is never refilled with new values. That's why there will be such warning about the empty list in each validation iteration. I don't think it will affect training, as (1) the self.log_steps list is for logging purposes, and (2) the warning is thrown in the code snippet used for frequency checking, not for gradient updates. You can also follow this question for more information: https://github.com/CompVis/latent-diffusion/issues/299

**Comment by ziqihuangg** [comment]
Hi, it seems there is no follow-up question regarding this issue. I'm closing the issue, but feel free to re-open it if you still haven't solved it.
